# Generated by Django 2.2 on 2020-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flagged',
            field=models.PositiveIntegerField(default=0, help_text='Flag a wrong question', verbose_name='Flag Wrong Questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(blank=True, help_text='Right Answer of question, must be an Integer. eg - 1 for option a, 2 for option b and so on', max_length=10, null=True, verbose_name='right answer'),
        ),
    ]
