# Generated by Django 3.0.5 on 2020-11-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answeroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='option',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
