# Generated by Django 3.0.5 on 2021-01-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201128_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='correct',
            field=models.BooleanField(default=False, verbose_name=' '),
        ),
    ]
