# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unicorn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlineexamresult',
            old_name='uid1',
            new_name='roll_number',
        ),
        migrations.RemoveField(
            model_name='offlineexamresult',
            name='uid2',
        ),
    ]
