# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unicorn', '0002_auto_20190107_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
