# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unicorn', '0003_auto_20190131_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=15),
        ),
    ]
