# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-01 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unicorn', '0005_auto_20191126_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
    ]
