# Generated by Django 2.2 on 2020-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.ManyToManyField(to='quiz.AnswerOptions', verbose_name='Answer Options'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(None, 'Choose Question Type'), ('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('integer', 'Answer in Integer'), ('paragraph', 'Paragraph Type')], default='mcq', max_length=50, verbose_name='type of question'),
        ),
    ]
