# Generated by Django 2.2 on 2020-07-02 17:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questionpaper',
            field=models.OneToOneField(blank=True, help_text='Questionpaper which will be given to user taking this quiz', null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.QuestionPaper', verbose_name='questionpaper'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date_time',
            field=models.DateTimeField(blank=True, help_text='Date-time after which this quiz will be deactivated automatically', null=True, verbose_name='End date-time of quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Instructions to show users before they take exam', verbose_name='instructions of quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public quizzes will appear in quiz catalogue and can be taken by users registered on site', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Publish the quiz, won't be accessible if you don't publish it", verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='multiple_attempts_allowed',
            field=models.BooleanField(default=False, help_text='Is user allowed to attempt same quiz multiple time?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(help_text='Name of quiz', max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date-time from which this quiz will be active', verbose_name='Start date-time of quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='view_answerpaper',
            field=models.BooleanField(default=False, help_text='Is user allowed to view his test report after he submits the test!'),
        ),
    ]
