# Generated by Django 2.2 on 2020-07-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200723_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Attribute', verbose_name='Attribute'),
        ),
    ]
