# Generated by Django 2.2 on 2020-07-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_auto_20200722_1317'),
        ('quiz', '0002_auto_20200721_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answerpapers', to='participate.Participate'),
        ),
    ]
