# Generated by Django 2.2 on 2020-07-02 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200702_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration of quiz in minutes', verbose_name='Duration of quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='User which will be allowed to take test', null=True, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
