# Generated by Django 2.2 on 2020-06-25 12:28

import champsquarebackend.core.models.fields.autoslugfield
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200602_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', champsquarebackend.core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime when model is created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='datetime when model is updated last time')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('slug', champsquarebackend.core.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='slug')),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date-time of quiz')),
                ('end_date_time', models.DateTimeField(blank=True, null=True, verbose_name='End date-time of quiz')),
                ('duration', models.IntegerField(default=60, verbose_name='Duration of quiz')),
                ('total_marks', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions of quiz')),
                ('publish', models.BooleanField(default=False)),
                ('multiple_attempts_allowed', models.BooleanField(default=False)),
                ('view_answerpaper', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category', to='quiz.Category')),
                ('users', models.ManyToManyField(help_text='User which will be allowed to take test', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime when model is created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='datetime when model is updated last time')),
                ('shuffle_question', models.BooleanField(default=False)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(related_name='questions', to='quiz.Question', verbose_name='Questions')),
                ('quiz', models.OneToOneField(help_text='Quiz to which this question paper belongs', on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime when model is created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='datetime when model is updated last time')),
                ('attempt_number', models.IntegerField(verbose_name='Attempt number')),
                ('start_time', models.DateTimeField(verbose_name='Start time of paper')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time of paper')),
                ('last_active_time', models.DateTimeField(verbose_name='last active time of user')),
                ('user_ip', models.GenericIPAddressField(verbose_name='IP address of user')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionPaper')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
