# Generated by Django 2.2 on 2020-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200727_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpaper',
            name='status',
            field=models.CharField(blank=True, max_length=128, verbose_name='Status of Test'),
        ),
    ]
