# Generated by Django 2.2 on 2020-07-22 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answerpaper_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpaper',
            name='participant_number',
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='unique_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
