# Generated by Django 2.2 on 2020-07-25 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_auto_20200725_1608'),
        ('quiz', '0003_auto_20200725_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='abstractattribute_ptr',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='attribute',
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration of quiz in minutes', verbose_name='Duration of quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_date_time',
            field=models.DateTimeField(blank=True, help_text='Date-time after which this quiz will be deactivated automatically', null=True, verbose_name='End date-time of quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ip_restriction',
            field=models.BooleanField(default=False, help_text='User will be only able to resume test from same ip if turned on!', verbose_name='IP Restricted?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Publish the quiz, won't be accessible if you don't publish it", verbose_name='Is Published?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='multiple_attempts_allowed',
            field=models.BooleanField(default=False, help_text='Is user allowed to attempt same quiz multiple time?', verbose_name='Multiple Attempts Allowed?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='resume_interval',
            field=models.PositiveIntegerField(default=15, help_text='The time interval after which user will not be able to resume test', verbose_name='Resume Interval'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date-time from which this quiz will be active', verbose_name='Start date-time of quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='view_answerpaper',
            field=models.BooleanField(default=False, help_text='Is user allowed to view his test report after he submits the test!', verbose_name='Can see answer-paper?'),
        ),
        migrations.DeleteModel(
            name='AbstractAttribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
