# Generated by Django 2.2 on 2020-06-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answerpaper_category_questionpaper_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_options',
        ),
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='right answer'),
        ),
    ]
