# Generated by Django 2.2 on 2020-07-02 19:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200703_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Instructions to show users before they take exam', null=True, verbose_name='instructions of quiz'),
        ),
    ]
