# Generated by Django 2.2 on 2020-07-22 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answerpaper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='participants', through='participate.Participate', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
