# Generated by Django 2.2 on 2020-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200730_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question'], 'verbose_name': 'Answer submitted by user', 'verbose_name_plural': 'Answers submitted by user'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ip_restriction',
            field=models.BooleanField(default=True, help_text='User will be only able to resume test from same ip if turned on!', verbose_name='IP Restricted?'),
        ),
    ]
