# Generated by Django 2.2 on 2020-07-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200703_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='users',
        ),
    ]
