# Generated by Django 2.2 on 2020-07-08 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200708_1449'),
        ('quiz', '0007_remove_quiz_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpaper',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='last_active_time',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='user_ip',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='users',
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='Is test started?'),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Is Test Submitted?'),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Access Time'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(related_name='includes', to='question.Question', verbose_name='Questions'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('answer', models.CharField(blank=True, max_length=128, verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is this answer correct?')),
                ('points', models.FloatField(default=0.0, verbose_name='points gained')),
                ('status', models.CharField(choices=[('unattempted', 'Not Attempted'), ('skipped', 'Skipped'), ('answered', 'Answered'), ('marked', 'Marked For Review'), ('answered_and_marked', 'Answered & Marked For Review')], default='unattempted', max_length=30, verbose_name='Status of Answer')),
                ('time_taken', models.FloatField(default=0.0, help_text='Time Spent on particular question', verbose_name='Time Taken')),
                ('answerpaper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answerpaper', to='quiz.AnswerPaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.Question')),
            ],
            options={
                'verbose_name': 'Answer submitted by user',
                'verbose_name_plural': 'Answers submitted by user',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='answer',
            field=models.ManyToManyField(related_name='answers', to='quiz.Answer', verbose_name='Answers'),
        ),
    ]
