# Generated by Django 2.2 on 2020-07-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_auto_20200708_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpaper',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='question_paper',
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End time of paper'),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Is trial?'),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='participant_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time of paper'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='quiz.AnswerPaper', verbose_name='AnswerPaper'),
        ),
        migrations.AlterField(
            model_name='answerpaper',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answerpapers', to='quiz.Quiz'),
        ),
    ]
