# Generated by Django 2.2 on 2020-07-09 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200709_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(blank=True, default=1, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
