# Generated by Django 2.2 on 2020-07-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200709_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('unvisited', 'Not Visited'), ('unanswered', 'Unanswered'), ('answered', 'Answered'), ('marked', 'Marked For Review'), ('answered_marked', 'Answered & Marked For Review')], default='unvisited', max_length=30, verbose_name='Status of Answer'),
        ),
    ]
