# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_section',
            field=models.CharField(blank=True, choices=[('sec1', 'Section One'), ('sec2', 'Section Two'), ('sec3', 'Section Three'), ('sec4', 'Section Four')], default='sec3', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematics'), ('biology', 'Biology')], default='mathematics', max_length=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(default='Jee Main Mock 1 Maths', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('integer', 'Answer in Integer'), ('paragraph', 'Paragraph Type'), ('match', 'Matching Type')], default='mcq', max_length=24),
        ),
    ]
