# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-27 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0002_auto_20181213_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpaper',
            name='questions_answered',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='questions_marked_for_review',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='questions_unanswered',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='questions_visited',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='right_answer_num',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='unanswered_question_num',
        ),
        migrations.RemoveField(
            model_name='answerpaper',
            name='wrong_answer_num',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('0', 'Not Visited'), ('1', 'Not Answered'), ('2', 'Answered'), ('3', 'Marked For Review'), ('4', 'Answered And Marked For Review')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=180, verbose_name='Duration of quiz in minutes'),
        ),
    ]
