# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0003_auto_20190127_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_point',
            field=models.FloatField(default=-1.0),
        ),
    ]
