# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0004_question_negative_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
