# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0005_auto_20190128_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(default='Jee Main Mock 2 Maths', max_length=256),
        ),
    ]
