# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0006_auto_20190131_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(default='Jee Main Mock 3 Maths', max_length=256),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
