# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0007_auto_20190309_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='instruction_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pwd',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(default='Ankur Online Test - 1 Maths Set - 2', max_length=256),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_criteria',
            field=models.FloatField(default=30, verbose_name='Passing percentage'),
        ),
    ]
