# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-26 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0008_auto_20190915_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='negative_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_section',
            field=models.CharField(blank=True, choices=[('sec1', 'Section One'), ('sec2', 'Section Two'), ('sec3', 'Section Three'), ('sec4', 'Section Four')], default='sec2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(default='Roots Online Test - 3 Mathematics Sec - 2', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('integer', 'Answer in Integer'), ('paragraph', 'Paragraph Type'), ('match', 'Matching Type')], default='integer', max_length=24),
        ),
    ]
