# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-01 17:24
from __future__ import unicode_literals

import Uscholar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0009_auto_20191126_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrentuser',
            name='concurrent_user',
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_point',
            field=models.FloatField(default=Uscholar.models.get_default_negative_point),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_section',
            field=models.CharField(blank=True, choices=[('sec1', 'Section One'), ('sec2', 'Section Two'), ('sec3', 'Section Three'), ('sec4', 'Section Four')], default=Uscholar.models.get_default_question_sec, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematics'), ('biology', 'Biology')], default=Uscholar.models.get_default_question_subject, max_length=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='summary',
            field=models.CharField(default=Uscholar.models.get_default_question_summary, max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('integer', 'Answer in Integer'), ('paragraph', 'Paragraph Type'), ('match', 'Matching Type')], default=Uscholar.models.get_default_question_type, max_length=24),
        ),
        migrations.DeleteModel(
            name='ConcurrentUser',
        ),
    ]
