# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-04 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0010_auto_20200101_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='integertestcase',
            name='correct',
            field=models.FloatField(default=None),
        ),
    ]
