# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0011_auto_20200104_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
