# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0012_auto_20200104_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
