# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0013_answer_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time_spent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
