# Generated by Django 3.0.5 on 2020-04-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('full_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfflineExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('batch', models.CharField(blank=True, max_length=40, null=True)),
                ('correct', models.CharField(blank=True, max_length=30, null=True)),
                ('incorrect', models.CharField(blank=True, max_length=30, null=True)),
                ('full_marks', models.IntegerField(default=80)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('rank', models.CharField(blank=True, max_length=5, null=True)),
                ('marks', models.CharField(blank=True, max_length=5, null=True)),
                ('percentile', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('incorrect', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('offline_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unicorn.OfflineExam')),
            ],
        ),
    ]
