# Generated by Django 2.2 on 2020-06-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_record_type', models.CharField(choices=[('webcam', 'Webcam'), ('screen', 'Screen Recording')], max_length=20)),
                ('video_id', models.CharField(max_length=50)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uscholar.AnswerPaper')),
            ],
        ),
    ]
