# Generated by Django 2.2 on 2020-06-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0002_videorecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videorecord',
            old_name='video_id',
            new_name='name',
        ),
        migrations.AddField(
            model_name='videorecord',
            name='audio_file_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videorecord',
            name='video_file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
