# Generated by Django 2.2 on 2020-06-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempt', models.IntegerField(default=0)),
                ('num_correct', models.IntegerField(default=0)),
                ('num_wrong', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
            ],
        )
    ]
