# Generated by Django 3.0.5 on 2020-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempt', models.IntegerField(default=0)),
                ('num_correct', models.IntegerField(default=0)),
                ('num_wrong', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(default=0)),
                ('user_answer', models.CharField(max_length=5)),
                ('right_answer', models.CharField(max_length=5)),
            ],
        ),
    ]
