# Generated by Django 3.0.5 on 2020-04-23 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JeeMain', '0001_initial'),
        ('Uscholar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uscholar.Question'),
        ),
        migrations.AddField(
            model_name='result',
            name='answer_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uscholar.AnswerPaper'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
