# Generated by Django 2.2 on 2020-07-26 05:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime when model is created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='datetime when model is updated last time')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('webcam', 'Webcam'), ('screen', 'Screen Recording')], max_length=20, verbose_name='Video Type')),
                ('record_id', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url of video')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is video file processed?')),
            ],
            options={
                'verbose_name': 'Video Record',
                'verbose_name_plural': 'Video Records',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
