# Generated by Django 2.2 on 2020-07-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200726_1120'),
        ('monitoring', '0002_videorecord_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorecord',
            name='participant',
        ),
        migrations.AddField(
            model_name='videorecord',
            name='answerpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='quiz.AnswerPaper'),
        ),
    ]
