# Generated by Django 2.2 on 2020-07-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20200727_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecord',
            name='answerpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='quiz.AnswerPaper'),
        ),
    ]
