# Generated by Django 2.2 on 2020-07-08 09:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0008_auto_20200708_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime when model is created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='datetime when model is updated last time')),
                ('number', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Participation number')),
                ('start_time', models.DateTimeField(verbose_name='Start time of paper')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time of paper')),
                ('last_active_time', models.DateTimeField(verbose_name='last active time of user')),
                ('user_ip', models.GenericIPAddressField(verbose_name='IP address of user')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='Status of Test')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quiz', verbose_name='Quiz')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Participate',
                'verbose_name_plural': 'Participates',
                'ordering': ['-start_time'],
                'abstract': False,
            },
        ),
    ]
