# Generated by Django 2.2 on 2020-07-21 06:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='used to store metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime when model is created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='datetime when model is updated last time')),
                ('number', models.UUIDField(db_index=True, unique=True, verbose_name='Participation number')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time of paper')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time of paper')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address of user')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='Status of Test')),
            ],
            options={
                'verbose_name': 'Participate',
                'verbose_name_plural': 'Participates',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
