# Generated by Django 2.2 on 2020-07-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('quiz', '0001_initial'),
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='answerpaper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.AnswerPaper', verbose_name='AnswerPaper'),
        ),
        migrations.AddField(
            model_name='participate',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='quiz.Quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='participate',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='Site'),
        ),
    ]
