# Generated by Django 2.2 on 2020-07-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200709_1727'),
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate',
            name='last_active_time',
        ),
        migrations.AddField(
            model_name='participate',
            name='answerpaper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.AnswerPaper', verbose_name='AnswerPaper'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='quiz.Quiz', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time of paper'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
