# Generated by Django 2.2 on 2020-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0002_auto_20200709_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='number',
            field=models.UUIDField(db_index=True, unique=True, verbose_name='Participation number'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address of user'),
        ),
    ]
