# Generated by Django 2.2 on 2020-07-22 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0003_participate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Participation number'),
        ),
    ]
