# Generated by Django 2.2 on 2020-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0003_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='video_monitoring_enabled',
            field=models.BooleanField(default=True, help_text='Turn on/off video monitoring which includes webcam and screen recording', verbose_name='Video Monitoring Enabled?'),
        ),
    ]
