# Generated by Django 2.2 on 2020-07-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_auto_20200725_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_published',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active user will be able to take quiz', verbose_name='Is Published?'),
        ),
    ]
