# Generated by Django 2.2 on 2020-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_participant_video_monitoring_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user_ip',
        ),
    ]
