# Generated by Django 2.2 on 2020-07-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_auto_20200722_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate',
            name='status',
        ),
    ]
