# Generated by Django 2.2 on 2020-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0005_remove_participant_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ip_restriction',
            field=models.BooleanField(default=True, help_text='User will be only able to resume test from same ip if turned on!', verbose_name='IP Restricted?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='view_answerpaper',
            field=models.BooleanField(default=True, help_text='Is user allowed to view his test report after he submits the test!', verbose_name='Can see answer-paper?'),
        ),
    ]
