# Generated by Django 2.2 on 2020-07-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0006_auto_20200731_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='otp_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Otp code to access test'),
        ),
    ]
