# Generated by Django 2.2 on 2020-07-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0007_participant_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='otp_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Otp code to access test'),
        ),
    ]
