# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uscholar', '0005_auto_20190128_2359'),
        ('JeeMain', '0002_remove_result_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='question_paper',
        ),
        migrations.AddField(
            model_name='result',
            name='answer_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Uscholar.AnswerPaper'),
            preserve_default=False,
        ),
    ]
